version: 2

sources:
  - name: staging
    database: de-zoomcamp123   # your GCP project ID
    schema: nytaxi                           # your dataset

    tables:
      - name: green_tripdata
      - name: yellow_tripdata